"""Generated gloss regions.

Documents carry one-line glosses of load-bearing terms between marker
comments:

    <!-- gloss:mechanism -->A prescribed input-to-output relation ...<!-- /gloss -->

The text between the markers is generated from the term's tutorial definition
(the confirmed edge the tutorial_definitions view selects; its gl:gloss, else
its text) and is changed only by changing the glossary. `render` writes it;
`check` fails when it is stale or names a term with no confirmed tutorial
definition.
"""

from __future__ import annotations

import re
from pathlib import Path

from rdflib import RDF, Graph

from .graph import gloss_of, primary, resolve_term, short_id, tutorial_definitions
from .namespaces import GL, PACKAGE_DIR, RENDER_TARGETS, REPO_DIR

GLOSS_RE = re.compile(r"<!-- gloss:(?P<id>[a-z0-9-]+) -->(?P<body>.*?)<!-- /gloss -->", re.DOTALL)


def target_files(repo: Path) -> list[Path]:
    files: list[Path] = []
    for pattern in RENDER_TARGETS:
        files += sorted(repo.glob(pattern))
    return [f for f in files if f.is_file()]


def expected_gloss(graph: Graph, term_key: str, root: Path = PACKAGE_DIR) -> str | None:
    term = resolve_term(graph, term_key)
    if term is None:
        return None
    row = primary(tutorial_definitions(graph, root).get(term, []))
    return gloss_of(graph, row["def"]) if row else None


DOCS_PAGE = "docs/glossary.md"  # the docs-page target: generated whole, present wherever the repo has a docs/ directory
PAGE_HEADER = "<!-- generated by `uv run python -m glossary render`; do not edit by hand -->"
PAGE_KINDS = (("conceptual", "Idea"), ("formal", "Formal semantics"), ("didactic", "Story"), ("bridge", "Tutorial"))


def docs_page_path(repo: Path) -> Path | None:
    """The generated page, or None when the repo has no docs/ directory (for example a bare fixture)."""
    return repo / DOCS_PAGE if (repo / "docs").is_dir() else None


def expected_page(graph: Graph, root: Path = PACKAGE_DIR) -> str:
    """The glossary page: per term (sorted by label) the one-line gloss and its confirmed sources by kind."""
    edges: dict = {}
    for d in graph.subjects(RDF.type, GL.Definition):
        src = graph.value(d, GL.source)
        if graph.value(d, GL.status) != GL.confirmed or src is None:
            continue
        rank = graph.value(src, GL.rank)
        edges.setdefault(graph.value(d, GL["term"]), []).append({
            "kind": str(graph.value(src, GL.kind)).removeprefix(str(GL)),
            "source": str(graph.value(src, GL.label)),
            "locator": str(graph.value(d, GL.locator)),
            "rank": int(rank) if rank is not None else 0,
            "def": str(d),
        })
    terms = sorted((t for t in edges if t is not None), key=lambda t: (str(graph.value(t, GL.label)).lower(), str(t)))
    lines = [PAGE_HEADER, "", "# Glossary"]
    for t in terms:
        lines += ["", f"## {graph.value(t, GL.label)}", ""]
        gloss = expected_gloss(graph, short_id(t), root)
        if gloss:
            lines += [gloss, ""]
        lines += ["Sources", ""]
        for kind, heading in PAGE_KINDS:
            rows = sorted((r for r in edges[t] if r["kind"] == kind),
                          key=lambda r: (r["rank"], r["source"].lower(), r["locator"], r["def"]))
            if rows:
                lines.append(f"- {heading}")
                lines += [f"  - {r['source']}, {r['locator']}" for r in rows]
    return "\n".join(lines) + "\n"


def render(graph: Graph, repo: Path = REPO_DIR, root: Path = PACKAGE_DIR, *, write: bool = True) -> list[Path]:
    """Rewrite stale gloss regions and the docs page. Returns the files that changed (or would change)."""
    changed: list[Path] = []
    page = docs_page_path(repo)
    if page is not None:
        want = expected_page(graph, root)
        if not page.exists() or page.read_text(encoding="utf-8") != want:
            changed.append(page)
            if write:
                page.write_text(want, encoding="utf-8")
    for f in target_files(repo):
        text = f.read_text(encoding="utf-8")

        def sub(m: re.Match) -> str:
            want = expected_gloss(graph, m.group("id"), root)
            if want is None:
                return m.group(0)
            return f"<!-- gloss:{m.group('id')} -->{want}<!-- /gloss -->"

        new = GLOSS_RE.sub(sub, text)
        if new != text:
            changed.append(f)
            if write:
                f.write_text(new, encoding="utf-8")
    return changed
