from __future__ import annotations

from pathlib import Path

from glossary.check import run_check
from glossary.graph import load_graph
from glossary.render import render

GLOSS = "Mechanisms carried by logical components."


def write(repo: Path, body: str) -> Path:
    f = repo / "AGENTS.md"
    f.write_text(body)
    return f


def test_stale_marker_is_an_error_and_render_fixes_it(root: Path, repo: Path) -> None:
    f = write(repo, "Logical: <!-- gloss:logical -->old text<!-- /gloss -->\n")
    assert any(x.code == "gloss-drift" for x in run_check(root, repo))
    changed = render(load_graph(root), repo, root)
    assert changed == [f]
    assert f.read_text() == f"Logical: <!-- gloss:logical -->{GLOSS}<!-- /gloss -->\n"
    assert not [x for x in run_check(root, repo) if x.level == "error"]


def test_render_is_idempotent(root: Path, repo: Path) -> None:
    write(repo, "<!-- gloss:logical -->x<!-- /gloss -->")
    render(load_graph(root), repo, root)
    assert render(load_graph(root), repo, root) == []


def test_marker_for_unconfirmed_term_is_an_error(root: Path, repo: Path) -> None:
    write(repo, "<!-- gloss:function -->whatever<!-- /gloss -->")
    assert any(x.code == "gloss-drift" for x in run_check(root, repo))


def test_marker_for_unknown_term_is_an_error(root: Path, repo: Path) -> None:
    write(repo, "<!-- gloss:nothing -->x<!-- /gloss -->")
    assert any(x.code == "gloss-drift" for x in run_check(root, repo))


def test_text_outside_markers_is_untouched(root: Path, repo: Path) -> None:
    body = "before <!-- gloss:logical -->x<!-- /gloss --> after\nno markers here\n"
    f = write(repo, body)
    render(load_graph(root), repo, root)
    assert f.read_text().startswith("before ") and f.read_text().endswith(" after\nno markers here\n")


def docs_repo(repo: Path) -> Path:
    (repo / "docs").mkdir()
    return repo / "docs" / "glossary.md"


def test_docs_page_is_rendered_sorted_and_checked(root: Path, repo: Path) -> None:
    page = docs_repo(repo)
    assert render(load_graph(root), repo, root) == [page]
    text = page.read_text()
    assert text.startswith("<!-- generated by `uv run python -m glossary render`; do not edit by hand -->\n\n# Glossary\n")
    # only terms with a confirmed edge; "function" has none; sources grouped by kind
    assert "## function" not in text
    assert text.index("## logical") > 0
    assert f"\n{GLOSS}\n" in text
    assert "- Idea\n  - Canon, p. 5\n" in text
    assert "- Tutorial\n  - This tutorial's gloss.\n" in text  # its only refines target is proposed, so not named
    assert "AGENTS.md" not in text
    assert "Video" not in text  # proposed only
    assert render(load_graph(root), repo, root) == []
    assert not [x for x in run_check(root, repo) if x.level == "error"]


def test_docs_page_edited_by_hand_or_missing_is_an_error(root: Path, repo: Path) -> None:
    page = docs_repo(repo)
    assert any(x.code == "docs-page" for x in run_check(root, repo))  # missing
    render(load_graph(root), repo, root)
    page.write_text(page.read_text() + "hand edit\n")
    assert any(x.code == "docs-page" for x in run_check(root, repo))
    assert render(load_graph(root), repo, root, write=False) == [page]
    render(load_graph(root), repo, root)
    assert not [x for x in run_check(root, repo) if x.level == "error"]


def test_docs_page_terms_sorted_case_insensitively(tmp_path: Path, repo: Path) -> None:
    from .conftest import DEFS, TERMS, make_root
    terms = TERMS + 'glid:term-b a gl:Term ; gl:label "Beta" .\nglid:term-a a gl:Term ; gl:label "alpha" .\n'
    defs = dict(DEFS)
    defs["extra"] = DEFS["canon"].split("glid:def-canon--logical")[0] + "".join(
        f'glid:def-canon--{k} a gl:Definition ; gl:source glid:src-canon ; gl:term glid:term-{k} ; '
        f'gl:text "t" ; gl:locator "p. 1" ; gl:status gl:confirmed ; gl:confirmedBy "Z" .\n' for k in ("b", "a"))
    r = make_root(tmp_path, terms=terms, defs=defs)
    page = docs_repo(repo)
    render(load_graph(r), repo, r)
    heads = [ln for ln in page.read_text().splitlines() if ln.startswith("## ")]
    assert heads == ["## alpha", "## Beta", "## logical"]


FORMAL_SOURCE = """glid:src-formal a gl:Source ; gl:label "Formal" ; gl:edition "1" ; gl:sourceKind gl:Repository ;
    gl:kind gl:formal ; gl:rank 2 ; gl:commit "def456" .
"""


def make_page_root(tmp_path: Path, extra_defs: str, extra_terms: str = "") -> Path:
    from .conftest import DEFS, SOURCES, TERMS, make_root
    defs = dict(DEFS)
    defs["extra"] = DEFS["canon"].split("glid:def-canon--logical")[0] + extra_defs
    return make_root(tmp_path, sources=SOURCES + FORMAL_SOURCE, terms=TERMS + extra_terms, defs=defs)


def edge(name: str, src: str, term: str, locator: str, extra: str = "") -> str:
    return (f'glid:def-{name} a gl:Definition ; gl:source glid:src-{src} ; gl:term glid:term-{term} ; '
            f'gl:text "t" ; gl:locator "{locator}" ; gl:status gl:confirmed ; gl:confirmedBy "Z" {extra}.\n')


def test_kind_order_and_within_kind_order(tmp_path: Path, repo: Path) -> None:
    extra = "".join([
        edge("tut--zeta", "tutorial", "zeta", "x", "; gl:gloss \"g\" "),
        edge("video--zeta", "video", "zeta", "2:00"),
        edge("canon--zeta-b", "canon", "zeta", "p. 5"),
        edge("canon--zeta-a", "canon", "zeta", "p. 3"),
    ])
    r = make_page_root(tmp_path, extra, 'glid:term-zeta a gl:Term ; gl:label "zeta" .\n')
    page = docs_repo(repo)
    render(load_graph(r), repo, r)
    section = page.read_text().split("## zeta")[1]
    assert section.index("- Idea") < section.index("- Story") < section.index("- Tutorial")
    # same kind, rank and source: locator order (lexicographic and natural agree here; neither is pinned as intended)
    assert section.index("Canon, p. 3") < section.index("Canon, p. 5")


def test_render_without_write_and_dry_run_leave_the_page_unchanged(root: Path, repo: Path) -> None:
    from typer.testing import CliRunner

    from glossary.cli import app
    page = docs_repo(repo)
    page.write_text("stale\n")
    before = page.read_bytes()
    assert render(load_graph(root), repo, root, write=False) == [page]
    assert page.read_bytes() == before
    res = CliRunner().invoke(app, ["render", "--dry-run", "--root", str(root), "--repo", str(repo)])
    assert res.exit_code == 1 and "would change docs/glossary.md" in res.output
    assert page.read_bytes() == before


def test_page_skipped_without_docs_dir_and_checked_with_it(root: Path, repo: Path) -> None:
    assert render(load_graph(root), repo, root) == []
    assert not (repo / "docs").exists()
    assert not [x for x in run_check(root, repo) if x.code == "docs-page"]
    (repo / "docs").mkdir()
    assert any(x.code == "docs-page" for x in run_check(root, repo))


def test_locators_lose_pdf_indices_only(tmp_path: Path, repo: Path) -> None:
    extra = "".join([
        edge("canon--zeta-a", "canon", "zeta", "Sec. 3.2, p. 9 (PDF 7)"),
        edge("canon--zeta-b", "canon", "zeta", "PDF 12"),
        edge("canon--zeta-c", "canon", "zeta", "Part 3, 1:56"),
    ])
    r = make_page_root(tmp_path, extra, 'glid:term-zeta a gl:Term ; gl:label "zeta" .\n')
    page = docs_repo(repo)
    render(load_graph(r), repo, r)
    text = page.read_text()
    assert "PDF" not in text
    assert "  - Canon, Sec. 3.2, p. 9\n" in text and "  - Canon, Part 3, 1:56\n" in text
    from glossary.render import display_locator
    assert display_locator("PDF 12") == "" and display_locator("p. 4 (PDF 2)") == "p. 4"
    assert "(PDF 7)" in (r / "definitions" / "extra.ttl").read_text()  # the stored graph string is unchanged


def test_tutorial_entry_names_refined_sources_and_other_terms(tmp_path: Path, repo: Path) -> None:
    extra = "".join([
        edge("canon--zeta", "canon", "zeta", "p. 1"),
        edge("canon--other", "canon", "other", "p. 2"),
        edge("video--other", "video", "other", "1:00"),
        edge("tut--zeta", "tutorial", "zeta", "AGENTS.md Part 1", "; gl:refines glid:def-canon--zeta "),
        edge("tut--mine", "tutorial", "mine", "AGENTS.md Part 1",
             "; gl:refines glid:def-canon--other, glid:def-video--other, glid:def-canon--zeta "),
    ])
    terms = ('glid:term-zeta a gl:Term ; gl:label "zeta" .\nglid:term-other a gl:Term ; gl:label "other" .\n'
             'glid:term-mine a gl:Term ; gl:label "mine" .\n')
    r = make_page_root(tmp_path, extra, terms)
    page = docs_repo(repo)
    render(load_graph(r), repo, r)
    text = page.read_text()
    zeta = text.split("## zeta")[1].split("\n## ")[0]
    assert "- Tutorial\n  - This tutorial's gloss refines Canon.\n" in zeta
    mine = text.split("## mine")[1].split("\n## ")[0]
    assert "  - This tutorial's gloss refines other in Canon; Video and zeta in Canon.\n" in mine
    assert "AGENTS.md" not in text


def test_departure_note_derived_from_differs_from(root: Path, repo: Path) -> None:
    page = docs_repo(repo)
    render(load_graph(root), repo, root)
    # in the fixture the tutorial edge differs from the Canon edge; the note names that edge's source
    assert page.read_text().endswith("This tutorial uses this term differently from Canon.\n")
    assert page.read_text().count("differently from") == 1


ZETA = 'glid:term-zeta a gl:Term ; gl:label "zeta" .\n'


def tutorial_lines(r: Path, repo: Path, term: str = "zeta") -> list[str]:
    page = docs_repo(repo)
    render(load_graph(r), repo, r)
    section = page.read_text().split(f"## {term}")[1].split("\n## ")[0]
    return section.split("- Tutorial\n")[1].splitlines()


def test_own_term_refines_names_only_the_refined_sources(tmp_path: Path, repo: Path) -> None:
    extra = "".join([
        edge("canon--zeta", "canon", "zeta", "p. 1"),
        edge("video--zeta", "video", "zeta", "1:00"),
        edge("tut--zeta", "tutorial", "zeta", "x", "; gl:refines glid:def-video--zeta "),
    ])
    line = tutorial_lines(make_page_root(tmp_path, extra, ZETA), repo)[0]
    assert line == "  - This tutorial's gloss refines Video."


def test_refines_of_an_unconfirmed_edge_is_not_named(tmp_path: Path, repo: Path) -> None:
    extra = "".join([
        edge("canon--zeta", "canon", "zeta", "p. 1"),
        'glid:def-video--zeta a gl:Definition ; gl:source glid:src-video ; gl:term glid:term-zeta ; '
        'gl:text "t" ; gl:locator "1:00" ; gl:status gl:proposed .\n',
        edge("tut--zeta", "tutorial", "zeta", "x", "; gl:refines glid:def-canon--zeta, glid:def-video--zeta "),
    ])
    line = tutorial_lines(make_page_root(tmp_path, extra, ZETA), repo)[0]
    assert line == "  - This tutorial's gloss refines Canon."
    assert "Video" not in line


def test_only_unconfirmed_refines_falls_back(tmp_path: Path, repo: Path) -> None:
    extra = "".join([
        'glid:def-video--zeta a gl:Definition ; gl:source glid:src-video ; gl:term glid:term-zeta ; '
        'gl:text "t" ; gl:locator "1:00" ; gl:status gl:proposed .\n',
        edge("tut--zeta", "tutorial", "zeta", "x", "; gl:refines glid:def-video--zeta "),
    ])
    assert tutorial_lines(make_page_root(tmp_path, extra, ZETA), repo) == ["  - This tutorial's gloss."]


def test_no_refines_uses_the_fallback_line(tmp_path: Path, repo: Path) -> None:
    extra = edge("tut--zeta", "tutorial", "zeta", "x")
    assert tutorial_lines(make_page_root(tmp_path, extra, ZETA), repo) == ["  - This tutorial's gloss."]


def test_own_and_other_term_refines_together(tmp_path: Path, repo: Path) -> None:
    extra = "".join([
        edge("canon--zeta", "canon", "zeta", "p. 1"),
        edge("video--zeta", "video", "zeta", "1:00"),
        edge("canon--other", "canon", "other", "p. 2"),
        edge("tut--zeta", "tutorial", "zeta", "x",
             "; gl:refines glid:def-canon--zeta, glid:def-canon--other "),
    ])
    terms = ZETA + 'glid:term-other a gl:Term ; gl:label "other" .\n'
    line = tutorial_lines(make_page_root(tmp_path, extra, terms), repo)[0]
    assert line == "  - This tutorial's gloss refines Canon and other in Canon."


def test_two_departures_give_two_sorted_notes(tmp_path: Path, repo: Path) -> None:
    extra = "".join([
        edge("canon--zeta", "canon", "zeta", "p. 1"),
        edge("video--zeta", "video", "zeta", "1:00"),
        edge("tut--zeta", "tutorial", "zeta", "x",
             "; gl:differsFrom glid:def-video--zeta, glid:def-canon--zeta "),
    ])
    r = make_page_root(tmp_path, extra, ZETA)
    page = docs_repo(repo)
    render(load_graph(r), repo, r)
    zeta = page.read_text().split("## zeta")[1].split("\n## ")[0]
    notes = [ln for ln in zeta.splitlines() if "differently from" in ln]
    assert notes == ["This tutorial uses this term differently from Canon.",
                     "This tutorial uses this term differently from Video."]


def test_attribution_sources_ordered_by_rank_not_label(tmp_path: Path, repo: Path) -> None:
    # Formal (rank 2) sorts before Video (rank 1) by label; rank wins
    extra = "".join([
        edge("formal--zeta", "formal", "zeta", "s. 1"),
        edge("video--zeta", "video", "zeta", "1:00"),
        edge("tut--zeta", "tutorial", "zeta", "x", "; gl:refines glid:def-formal--zeta, glid:def-video--zeta "),
    ])
    line = tutorial_lines(make_page_root(tmp_path, extra, ZETA), repo)[0]
    assert line == "  - This tutorial's gloss refines Video and Formal."


def test_kind_order_is_idea_formal_story_tutorial(tmp_path: Path, repo: Path) -> None:
    extra = "".join([
        edge("tut--zeta", "tutorial", "zeta", "x"),
        edge("video--zeta", "video", "zeta", "1:00"),
        edge("formal--zeta", "formal", "zeta", "s. 1"),
        edge("canon--zeta", "canon", "zeta", "p. 1"),
    ])
    r = make_page_root(tmp_path, extra, ZETA)
    page = docs_repo(repo)
    render(load_graph(r), repo, r)
    section = page.read_text().split("## zeta")[1]
    heads = [section.index(h) for h in ("- Idea", "- Formal semantics", "- Story", "- Tutorial")]
    assert heads == sorted(heads)
