from __future__ import annotations

from pathlib import Path

from glossary.check import run_check
from glossary.graph import load_graph
from glossary.render import render

GLOSS = "Mechanisms carried by logical components."


def write(repo: Path, body: str) -> Path:
    f = repo / "AGENTS.md"
    f.write_text(body)
    return f


def test_stale_marker_is_an_error_and_render_fixes_it(root: Path, repo: Path) -> None:
    f = write(repo, "Logical: <!-- gloss:logical -->old text<!-- /gloss -->\n")
    assert any(x.code == "gloss-drift" for x in run_check(root, repo))
    changed = render(load_graph(root), repo, root)
    assert changed == [f]
    assert f.read_text() == f"Logical: <!-- gloss:logical -->{GLOSS}<!-- /gloss -->\n"
    assert not [x for x in run_check(root, repo) if x.level == "error"]


def test_render_is_idempotent(root: Path, repo: Path) -> None:
    write(repo, "<!-- gloss:logical -->x<!-- /gloss -->")
    render(load_graph(root), repo, root)
    assert render(load_graph(root), repo, root) == []


def test_marker_for_unconfirmed_term_is_an_error(root: Path, repo: Path) -> None:
    write(repo, "<!-- gloss:function -->whatever<!-- /gloss -->")
    assert any(x.code == "gloss-drift" for x in run_check(root, repo))


def test_marker_for_unknown_term_is_an_error(root: Path, repo: Path) -> None:
    write(repo, "<!-- gloss:nothing -->x<!-- /gloss -->")
    assert any(x.code == "gloss-drift" for x in run_check(root, repo))


def test_text_outside_markers_is_untouched(root: Path, repo: Path) -> None:
    body = "before <!-- gloss:logical -->x<!-- /gloss --> after\nno markers here\n"
    f = write(repo, body)
    render(load_graph(root), repo, root)
    assert f.read_text().startswith("before ") and f.read_text().endswith(" after\nno markers here\n")


def docs_repo(repo: Path) -> Path:
    (repo / "docs").mkdir()
    return repo / "docs" / "glossary.md"


def test_docs_page_is_rendered_sorted_and_checked(root: Path, repo: Path) -> None:
    page = docs_repo(repo)
    assert render(load_graph(root), repo, root) == [page]
    text = page.read_text()
    assert text.startswith("<!-- generated by `uv run python -m glossary render`; do not edit by hand -->\n\n# Glossary\n")
    # only terms with a confirmed edge; "function" has none; sources grouped by kind
    assert "## function" not in text
    assert text.index("## logical") > 0
    assert f"\n{GLOSS}\n" in text
    assert "- Idea\n  - Canon, p. 5\n" in text
    assert "- Tutorial\n  - This tutorial, AGENTS.md\n" in text
    assert "Video" not in text  # proposed only
    assert render(load_graph(root), repo, root) == []
    assert not [x for x in run_check(root, repo) if x.level == "error"]


def test_docs_page_edited_by_hand_or_missing_is_an_error(root: Path, repo: Path) -> None:
    page = docs_repo(repo)
    assert any(x.code == "docs-page" for x in run_check(root, repo))  # missing
    render(load_graph(root), repo, root)
    page.write_text(page.read_text() + "hand edit\n")
    assert any(x.code == "docs-page" for x in run_check(root, repo))
    assert render(load_graph(root), repo, root, write=False) == [page]
    render(load_graph(root), repo, root)
    assert not [x for x in run_check(root, repo) if x.level == "error"]


def test_docs_page_terms_sorted_case_insensitively(tmp_path: Path, repo: Path) -> None:
    from .conftest import DEFS, TERMS, make_root
    terms = TERMS + 'glid:term-b a gl:Term ; gl:label "Beta" .\nglid:term-a a gl:Term ; gl:label "alpha" .\n'
    defs = dict(DEFS)
    defs["extra"] = DEFS["canon"].split("glid:def-canon--logical")[0] + "".join(
        f'glid:def-canon--{k} a gl:Definition ; gl:source glid:src-canon ; gl:term glid:term-{k} ; '
        f'gl:text "t" ; gl:locator "p. 1" ; gl:status gl:confirmed ; gl:confirmedBy "Z" .\n' for k in ("b", "a"))
    r = make_root(tmp_path, terms=terms, defs=defs)
    page = docs_repo(repo)
    render(load_graph(r), repo, r)
    heads = [ln for ln in page.read_text().splitlines() if ln.startswith("## ")]
    assert heads == ["## alpha", "## Beta", "## logical"]
