@startuml
' state rendering (no view declared; rendering ToasterDemo::Cycle directly)
<style>
root {
  BackGroundColor white
  FontName SansSerif
  FontSize 14
  FontColor black
  LineColor #181818
  HorizontalAlignment left
}
element {
  BackGroundColor white
  LineColor #181818
  LineThickness 0.5
  RoundCorner 0
  Shadowing 0.0
}
start, end, activityBar {
  BackGroundColor black
}
arrow {
  LineColor #181818
  LineThickness 1
  FontSize 13
}
note {
  BackGroundColor #FEFFDD
  FontSize 13
}
.usage {
  RoundCorner 20
}
.package {
  LineThickness 1.5
}
.region {
  LineStyle 4
}
</style>
skinparam wrapWidth 300
hide stereotype
hide empty description
state "**Cycle**\n<size:10>//«state def»//</size>" as n0 <<state def>> {
  state "**idle**\n<size:10>//«state»//</size>\ninitial" as n1 <<state>> <<usage>>
  state "**heating**\n<size:10>//«state»//</size>\ndo" as n2 <<state>> <<usage>>
  state "**ready**\n<size:10>//«state»//</size>" as n3 <<state>> <<usage>>
  state "**cancelled**\n<size:10>//«state»//</size>" as n4 <<state>> <<usage>>
  [*] --> n1
}
n1 --> n2 : accept Start
n2 --> n4 : accept Finish
n2 --> n4 : accept Cancel
n3 --> n1
n4 --> n1
@enduml
